apiVersion: v1
kind: Service
metadata:
  name: cafa6-service
spec:
  type: LoadBalancer
  selector:
    app: cafa6
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30001